from test_integrator import test_integral_of_constant_function, test_integral_of_linear_function, test_numpy_integrate_constant_function, test_numpy_integrate_linear_function, test_numba_integrate_constant_function, test_numba_integrate_linear_function

from test_integrator import test_midpoint_integral_of_constant_function, test_midpoint_integral_of_linear_function, test_numpy_midpoint_integrate_constant_function, test_numpymidpoint__integrate_linear_function, test_numba_midpoint_integrate_constant_function, test_numba_midpoint_integrate_linear_function
